spring.application.name=NusaCart

spring.datasource.url=jdbc:mysql://db.nusacart.biz.id/nusacart?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Atmin@NusaCart@2025

server.port=8080