spring.application.name=NusaCart

spring.datasource.url=jdbc:mysql://db.nusacart.biz.id/nusacart?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Atmin@NusaCart@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=900000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.keepalive-time=300000
server.port=6060

whatsapp.api.url=http://213.210.37.132:3000/send/message
whatsapp.api.username=admin
whatsapp.api.password=NusaCart@OTP@2025

logging.level.com.TryCatch.NusaCart.security.JwtAuthenticationFilter=DEBUG
logging.level.com.TryCatch.NusaCart.service.AuthService=DEBUG

# Disable favicon error logging
logging.level.org.springframework.web.servlet.resource.ResourceHttpRequestHandler=WARN

# Upload configuration
app.upload.dir=../backend/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB